pipeline{
    agent any
    stages{
        stage("checkout stage"){
            
            steps{
                echo "=====checkout stage====="
                checkout scmGit(branches: [[name: '*/beanstalk-project']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/SivaSuribabu/elasticbeanstalk.git']])
                if (env.BRANCH_NAME == "beanstalk-project"){
                    echo "checkout successful"
                }
            }
            
        }
        stage("build-stage"){
            when {
                expression { return false }
            }
            steps{
                sh "skipped"
            }
        }
    }
}